### ISSUE TITLE
ImportError: DLL load failed while importing _cext: Le module spécifié est introuvable.

### ISSUE THREAD

**Issue by Math6935** [fmckenna/OpenSeesInterpreter#1]
Good afternoon,

I installed the package opsvis successfully on my computer with Python, but when I try to import it, this error message is sent: 
ImportError: DLL load failed while importing _cext: Le module spécifié est introuvable.

I code with Python 3.10 on Pyzo.

Can anyone help me please ?

Thank you

**Comment by mhscott** [comment]
This is not an active repo. You should post this issue on the OpenSees message board or Facebook group
https://opensees.berkeley.edu/community/
https://www.facebook.com/groups/opensees
