### ISSUE TITLE
WARNING nodeDisp - failed to read int inputs

### ISSUE THREAD

**Issue by Math6935** [fmckenna/OpenSeesInterpreter#2]
Good afternoon,

I want to print the vertical deflection on a node, but the following error message is sent:
![Capture](https://github.com/fmckenna/OpenSeesInterpreter/assets/136455782/4995b704-1fd8-474e-af76-9d1216730c24)
![Capture2](https://github.com/fmckenna/OpenSeesInterpreter/assets/136455782/9f0cb502-5502-4d8b-ad59-c62b3514c201)

I don't understand this error message because what I wrote is an integer, it should work.

Thank you for your attention

**Comment by mhscott** [comment]
This is not an active repo. You should post this issue on the OpenSees message board or Facebook group
https://opensees.berkeley.edu/community/
https://www.facebook.com/groups/opensees
